//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbnobaIndia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLoginMaster
    {
        public int AdminLoginID { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string Password { get; set; }
        public string UserProfileImage { get; set; }
        public string Role { get; set; }
        public Nullable<bool> IsPasswordUpdated { get; set; }
        public Nullable<System.DateTime> PasswordUpdatedOn { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
    }
}
