//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbnobaIndia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLogin
    {
        public int UserId { get; set; }
        public string UserGUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Zip { get; set; }
        public string Country { get; set; }
        public string Profession { get; set; }
        public string Discipline { get; set; }
        public string FieldOfActivity { get; set; }
        public Nullable<bool> WantToReceiveDocEmail { get; set; }
        public Nullable<bool> IsPwdAutoGenerated { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> LoginAllowed { get; set; }
        public string AllowedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
